service: my-pet-sls

plugins:
  - serverless-offline
  - serverless-plugin-optimize

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

package:
  exclude:
    - node_modules/**
    - .git/**
    - .vscode/**
    - tests/**
    - docs/**

custom:
  webpack:
    webpackConfig: './webpack.config.js'
    includeModules: true

functions:
  health:
    handler: dist/handler.handler
    events:
      - httpApi:
          path: /health
          method: get
